### ISSUE TITLE
注册用户在add_user.php页面无响应

### ISSUE THREAD

**Issue by liunianbanbo** [hm081333/bbs#1]
无响应的意思就是地址栏显示在add_user.php，但是页面一片空白，离那个错误提示都没有

**Comment by liunianbanbo** [comment]
我在数据库找到的账号密码输入也在chklogin.php上报错。
Fatal error: Call to undefined function password_verify() in \var\html\platform-for-exchange-of-teachers-and-students-master\chklogin.php on line 28

	
	if($num_rows == 1)
	{
		//获得用户名
		$row = mysql_fetch_assoc($result);
		
		$hash = $row['password'];
		if(password_verify($password,$hash)){    **//这是第28行**

		//将用户名存如SESSION中
		$_SESSION['username'] = $row['username'];
		$_SESSION['user_auth'] = $row['auth'];

		//跳转到论坛主页面
		header("Location: index.php");
		}else{
			echo '<script>alert(\'用户名错误！\');window.history.back();</script>';
			exit();
		}
	}
	else {
		echo '<script>alert(\'用户名错误！\');window.history.back();</script>';
	    exit();
	}

**Comment by liunianbanbo** [comment]
哦，是我php版本太低了

**Comment by liunianbanbo** [comment]
一堆报错，果然还是强行忽略很明智

**Comment by hm081333** [comment]
我记得我当时是在php5.6的环境下做的。。。报错多是因为那时候在学校。。。学校的老师的教学质量上过学的都知道。。。so基本上是什么都不懂的情况下开发的。你环境换到5.6试一下。至于bug。。。估计得重写了。

**Comment by liunianbanbo** [comment]
强行忽略了一对报错，你要不介意我也拿来作为毕设的参考(抄袭)了，该有的功能都有，前端也很漂亮，颜色不喜欢，死气沉沉的

**Comment by hm081333** [comment]
前端样式的颜色你可以改啊。.框架是这个：http://materializecss.com/color.html。。但是我记得后台左边的选项栏在项目文件夹改到某些名称的时候会报错。。。

**Comment by liunianbanbo** [comment]
后台的root密码是什么，我记得那天好像登录上了，123？

**Comment by liunianbanbo** [comment]
对了，在反馈一个问题。开发一定要按规范来。
session start()的开启一定要放在文件的首行。你这里居然放在了config.inc.php的第64行。我到说在Mac上怎么打开就报错

**Comment by hm081333** [comment]
后台密码是123 账号是root
session。。。网上说的   调用session_start()不一定要把这个函数放在第一行，而是要保证在使用它之前，没有向浏览器输出过任何内容   所以就放config连接数据库上面

**Comment by hm081333** [comment]
话说我在linux上都没报错。。。mac居然报错。。

**Comment by liunianbanbo** [comment]
谢了。作业已抄完。前端的颜色全改了...过几天写报告糊弄毕业去

**Comment by liunianbanbo** [comment]
Mac上报错是真的，我查了两个小时的资料才确定。连自己电脑上的环境都重装了一遍

**Comment by hm081333** [comment]
666
